---
AWSTemplateFormatVersion: "2010-09-09"
Description: "This template will create EC2 instances"
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: Name
          Value: Test_instance
      InstanceType: 't2.micro'
      SubnetId: 'subnet-04ef127b711a9f463'
      ImageId: 'ami-0b0dcb5067f052a63'
      BlockDeviceMappings:
        - DeviceName: "/dev/sdm"
          Ebs: 
            VolumeType: "gp2"
            DeleteOnTermination: "true"
            VolumeSize: "10"
        - DeviceName: "/dev/sdk"
          NoDevice: {}
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          yum install -y https://s3.us-east-1.amazonaws.com/amazon-ssm-us-east-1/latest/linux_amd64/amazon-ssm-agent.rpm
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          yum install zip unzip -y
          unzip awscliv2.zip
          ./aws/install
          ln -s /usr/local/bin/aws /usr/sbin
  #     InstanceProfile: !Ref ManagedInstanceProfile
  # ManagedInstanceProfile:
  #   Type: AWS::IAM::InstanceProfile
  #   Properties:
  #     Path: "arn:aws:iam::311236944147:instance-profile/"
  #     Roles:
  #     - 'ssm-role'
  #     InstanceProfileName: 'ssm_role' 