Resources:
  MyEC2Instance:
    Description: 'EC2 Instance'
    Type: "AWS::EC2::Instance" 
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !FindInMap [MySubnet, "us-east-1c", Subnet]
      UserData:  
        Fn::Base64: |
          #!/bin/bash
          yum install -y https://s3.us-east-1.amazonaws.com/amazon-ssm-us-east-1/latest/linux_amd64/amazon-ssm-agent.rpm
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          yum install zip unzip -y
          unzip awscliv2.zip
          ./aws/install
          ln -s /usr/local/bin/aws /usr/sbin
      Tags:
        - Key: Name
          Value: NRtech_Server
        - Key: Production
          Value: Server1
      ImageId: !Ref InstanceAMI
      KeyName: "demolms"
      BlockDeviceMappings: 
        - DeviceName: "/dev/sdm"
          Ebs: 
            VolumeType: "io1"
            Iops: "200"
            DeleteOnTermination: "true"
            VolumeSize: "10"
        - DeviceName: "/dev/sdk"
          NoDevice: {}