AWSTemplateFormatVersion: "2010-09-09"

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: my-bucket-name
  MyBucketPolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
          Bucket:
            Ref: 'MyBucket'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal: 'aws::iam:groupname'
                Action: 's3:GetObject'
                Resource:
                  Fn::Join:
                    - ''
                    - - 'arn:aws:s3:::'
                      - Ref: 'MyBucket'
                      - '/*'

                      