AWSTemplateFormatVersion: '2010-09-09'
Resources:
  hmsLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: !Sub '${AWS::StackName}-hms-launch-template'
      LaunchTemplateData:
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            Groups:
              - sg-7c2270198example
              - sg-903004f88example
            DeleteOnTermination: true
        Placement:
          Tenancy: default
        ImageId: ami-04d5cc9b88example
        InstanceType: t3.medium
        BlockDeviceMappings: 
          - Ebs:
              VolumeSize: 15
              VolumeType: gp3
              DeleteOnTermination: true
              Encrypted: true
            DeviceName: /dev/xvdcz
        KeyName: MyKeyPair
  hmsASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref hmsLaunchTemplate
        Version: !GetAtt hmsLaunchTemplate.LatestVersionNumber
      MaxSize: '3'
      MinSize: '1'
      DesiredCapacity: '2'
      VPCZoneIdentifier:   
        - subnetIdAz1
        - subnetIdAz2
        - subnetIdAz3
      MetricsCollection: 
        - Granularity: 1Minute
          Metrics: 
            - GroupMinSize
            - GroupMaxSize
      Tags:
        - Key: Environment
          Value: Production
          PropagateAtLaunch: true
        - Key: Purpose
          Value: WebServerGroup
          PropagateAtLaunch: false